### ISSUE TITLE
Uvoz in zemljevid

### ISSUE THREAD

**Issue by jaanos** [UrbanRupnik/APPR-2020-21#1]
Pazi, da pri uvozu podatkov podaš pravo kodiranje znakov - pri meni namreč podatkov ne uvozi pravilno, zaradi česar potem tudi vizualizacija ne deluje. Svetujem, da namesto vgrajene funkcije `read.csv2` (s piko) za uvoz uporabiš funkcijo `read_csv2` (s podčrtajem) iz knjižnice `readr`, saj je ta bolj robustna, poleg tega pa ne povzroča zmede s podajanjem kodiranja znakov. Uvoz podatkov po starosti bi potem šel nekako tako:
```R
glava_starost_spol <- c("Meritev", "Starost", "Spol", "Leto", 
                        "SocialniTransferji", "Dohodek")
starosti <- c("0-17", "18-24", "25-49", "50-64", "65+")

starost_spol_vsi <- read_csv2("podatki/starost_spol.csv", skip=3,
  col_names=glava_starost_spol, locale=locale(encoding="Windows-1250")) %>%
  filter(Spol != "Spol - SKUPAJ") %>% select(-Meritev, -SocialniTransferji)

starost_spol <- starost_spol_vsi %>% filter(Starost != "Starostne skupine - SKUPAJ") %>%
  mutate(Starost=gsub("Starost ", "", Starost) %>%
              parse_factor(levels=starosti, ordered=TRUE))

spol <- starost_spol_vsi %>% filter(Starost == "Starostne skupine - SKUPAJ") %>%
  select(-Starost)
```
Tukaj je poskrbljeno za odstranitev nepotrebnih stolpcev ter za pretvorbo podatka o starostni skupini v urejen faktor - tako se bodo ti podatki na grafih prikazali v pravem vrstnem redu. Sumarni podatki so tukaj odstranjeni - za njihov izračun bi sicer potreboval še podatek o številu oseb v posamezni kategoriji, tako da so podatki, ki jih potrebuješ za drugi graf, spravljeni v svojo razpredelnico.

Opažam še, da kodo za zemljevid kličeš iz vzorčnega repozitorija - to ni potrebno in je nevarno, saj nimaš nadzora nad to kodo (lahko bi npr. podtaknil kako zlonamerno kodo). Program `uvozi.zemljevid.r` imaš v mapi `lib` in ga kličeš takrat, ko kličeš `libraries.r`. Svetujem, da tja tudi prestaviš vse uvoze knjižnic, ki jih imaš trenutno v `uvoz1.r` in `vizualizacija1.r`. Tako lahko vsakič pred začetkom dela poženeš `libraries.r`, da se uvozijo knjižnice (to se zgodi tudi na začetku prevajanja poročila).

Vidim, da po uvozu zemljevida ročno poskrbiš za pretvorbo v UTF-8 - to načeloma naj ne bi bilo potrebno, če podaš kodiranje znakov k `uvozi.zemljevid` (navadno se sicer piše `UTF-8` z velikimi črkami). Trenutno pride tudi do napake pri pripravi podatkov za zemljevid, saj razpredelnica `regije_19` ni definirana. Namesto tega bo dovolj, da podaš imena stolpcev - ker so ti številke, jih bo potrebno obdati z "backtick"-i (desni Alt+7 na slovenski tipkovnici):
```R
regije_8_19 <- regije %>%
  filter(Leto %in% c(2008, 2019)) %>%
  pivot_wider(names_from=Leto, values_from=Dohodek) %>%
  mutate(Rast = (((`2019` - `2008`) / `2008`) * 100))
```

**Comment by UrbanRupnik** [comment]
Hvala za komentar. Težave sem odpravil in popravil tudi pomanjkljivosti pri čiščenju podatkov ter dodal funkcije v `libraries.r`, tako da zdaj deluje tudi v rStudiu preko binderja.

Pri zemljevidu pa sem moral ročno pretvoriti kodiranje, saj mi (ne vem zakaj) ni `encoding="UTF-8"` znotraj `uvozi.zemljevid` že popravil imen regij v `zemljevid_regije$NAME_1`.

**Comment by UrbanRupnik** [comment]
Sem popravil tudi `libraries.r`.
