### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by UrbanRupnik** [UrbanRupnik/APPR-2020-21#3]
Pozdravljeni.
Če imate še kakšen komentar, sicer sem naredil kar sem si zamislil.

**Comment by jaanos** [comment]
Glede na to, da projekt deluje, bom dodal povezavo na repozitorij za zagovore, tako da se lahko z @alenFMF domeniš za termin zagovora. Če boš do takrat še kaj spreminjal, mi javi, da posodobim povezavo.

Edina pripomba, ki jo imam, je ta, da bi bilo dobro na grafu napovedi dohodka napovedne točke pobarvati z drugo barvo.

Še to: trenutno projekt ne deluje na Binderju, saj v osnovni sliki manjka paket `waffle`. Sem zdaj dal delat sliko - ko bo pripravljena (čez kako uro do dve), bi se morala zraven zgoraj omenjenega commita pojaviti zelena kljukica. Po tem bi moral projekt delovati (bo pa treba narediti nov commit, da se bo iz posodobljene osnovne ustvarila nova slika za tvoj projekt).

**Comment by UrbanRupnik** [comment]
Hvala za komentar, sem popravil barvo napovednih točk.

**Comment by jaanos** [comment]
V redu, sem posodobil.
